---
title: "Corona Virus Report"
author:
- familyname: Tsakis
  othernames: Alexi
  address: Monash Universtidy
  email: atsa0003@student.monash.edu
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries
library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
```

\section*{Country XX1 and YY1"}

\section*{Country XX2 and YY2}

\section*{Country Myanmar and Guernsey}

```{r}
library(lubridate)
options(scipen=10)
set.seed(96024)
data = read.csv("data/worldwidecases.csv")
sample(unique(data$countriesAndTerritories),2)

data = data %>%
  filter(countriesAndTerritories %in% c("Myanmar","Guernsey")) %>%
  mutate(day_of_year = yday(as.Date(dateRep,format='%d/%m/%Y'))) %>%
  mutate(pct_pop = (cases/popData2018)*100)

data %>%
  ggplot(aes(x=day_of_year,y=cases,col=countriesAndTerritories))+geom_line()

data %>%
  ggplot(aes(x=day_of_year,y=pct_pop,col=countriesAndTerritories))+geom_line()
```



